spring:
  application:
    name: linkedin-task
  security:
    oauth2:
      client:
        registration:
          linkedin:
            client-id: ${LINKEDIN_CLIENT_ID}
            client-secret: ${LINKEDIN_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/linkedin"
            scope: openid, profile, email
            client-name: LinkedIn

        provider:
          linkedin:
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            user-info-uri: https://api.linkedin.com/v2/userinfo
            jwk-set-uri: https://www.linkedin.com/oauth/openid/jwks
